sudo: required
services:
  - docker
  
before_install:
  - docker build -f Dockerfile.dev -t joelpatel/docker-react .

script:
  - docker run -e CI=true joelpatel/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "Docker-react-env"
#   bucket_name: "elasticbeanstalk-us-east-1-123456789012"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_key_id:
#     secure: $AWS_SECRET_KEY